#!/bin/bash

check() {
    sudo lxc-ls --running | grep -q $1
}

create() {
    local name="$1"
    local arch="$2"
    check $name && { echo "$name already created."; return 1; }
    export MIRROR="http://old-releases.ubuntu.com/ubuntu"
    export SECURITY_MIRROR="$MIRROR"
    sudo -E lxc-create -n $name -t ubuntu -- -r lucid -a $arch
    sudo rm /var/lib/lxc/$name/rootfs/dev/shm    # hack to make it work
    sudo lxc-start -n $name -d
    check $name && echo "$name running."
}

create u10_32 i386
create u10_64 x86_64
